"""empty message

Revision ID: 29eda93c20dc
Revises: fbdee63273ec
Create Date: 2019-07-14 15:03:18.414738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29eda93c20dc'
down_revision = 'fbdee63273ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('department', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('post', sa.String(), nullable=True))
    op.drop_constraint('applications_phone_key', 'applications', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('applications_phone_key', 'applications', ['phone'])
    op.drop_column('applications', 'post')
    op.drop_column('applications', 'department')
    # ### end Alembic commands ###
